BASENAME	= model

LIBSRCS		= \
			BVHMotion.cxx \
			Boundary.cxx \
			BoundaryElem.cxx \
			MatAdmin.cxx \
			Model.cxx \
			ModelTree.cxx

FKLINK		= \
			-lFK4_base.$(VERNAME) \
			-lFK4_math.$(VERNAME) \
			-lFK4_material.$(VERNAME) \
			-lFK4_shape.$(VERNAME)

FKLINK_G	= \
			-lFK4_base_g.$(VERNAME) \
			-lFK4_math_g.$(VERNAME) \
			-lFK4_material_g.$(VERNAME) \
			-lFK3_shape_g.$(VERNAME)

include ../makeinclude
