BASENAME	= model

LIBSRCS		= \
			BVHMotion.cxx \
			Boundary.cxx \
			BoundaryElem.cxx \
			MatAdmin.cxx \
			Model.cxx \
			ModelTree.cxx

FKLINK		= \
			-lFK3_base.$(VERNAME) \
			-lFK3_math.$(VERNAME) \
			-lFK3_material.$(VERNAME) \
			-lFK3_shape.$(VERNAME)

FKLINK_G	= \
			-lFK3_base_g.$(VERNAME) \
			-lFK3_math_g.$(VERNAME) \
			-lFK3_material_g.$(VERNAME) \
			-lFK3_shape_g.$(VERNAME)

include ../makeinclude
