BASENAME	= shader

LIBSRCS		= \
			ShaderBinder.cxx \
			ShaderParameter.cxx \
			ShaderProgram.cxx

FKLINK		= \
			-lFK3_math.$(VERNAME) \
			-lFK3_shape.$(VERNAME)

FKLINK_G	= \
			-lFK3_math_g.$(VERNAME) \
			-lFK3_shape_g.$(VERNAME)

include ../makeinclude
