BASENAME	= shader

LIBSRCS		= \
			ShaderBinder.cxx \
			ShaderParameter.cxx \
			ShaderProgram.cxx

FKLINK		= \
			-lFK3_math.$(VERNAME) \
			-lFK3_shape.$(VERNAME)

FKLINK_G	= \
			-lFK3_math_g.$(VERNAME) \
			-lFK3_shape_g.$(VERNAME)

GLSLSRCS	= $(shell /usr/bin/find ./GLSL -maxdepth 1 -name "*.glsl" -print)

GLSLOUTS	= $(GLSLSRCS:.glsl=.out)

include ../makeinclude

glsl : $(GLSLOUTS)

%.out : %.glsl
	./GLSL/glsl2out $<

ShaderProgram.o: GLSL/BuildIn.out
