#!/usr/bin/env perl

use File::Basename 'dirname';

$scriptName = $0;
$scriptName =~ s/^(\w)(:)/\/cygdrive\/$1/;
$scriptName =~ s/\\/\//g;
$dirName = dirname($scriptName);

@fileList = glob("$dirName/*.glsl");

foreach $glslName (@fileList) {
	next if $glslName !~ /.glsl$/;
	$outName = $glslName;
	$outName =~ s/.glsl$/.out/;

	open(INFILE, $glslName) || die "Can't Open $glslName : $!\n";
	open(OUTFILE, ">$outName") || die "Can't Open $outName : $!\n";

	print OUTFILE "R\"(\n";
	while(<INFILE>) {
		print OUTFILE $_;
	}
	print OUTFILE ")\"\n";	

	close(INFILE);
	close(OUTFILE);
}

0;
