BASENAME	= audio

LIBSRCS		= \
			Audio_Base.cxx \
			Audio_Buffer.cxx \
			Audio_Stream.cxx

FKLINK		= \
			-lFK4_base.$(VERNAME) \
			-lFK4_math.$(VERNAME) \
			-lFK4_model.$(VERNAME)

FKLINK_G	= \
			-lFK4_base_g.$(VERNAME) \
			-lFK4_math_g.$(VERNAME) \
			 -lFK4_model_g.$(VERNAME)

include ../makeinclude
