BASENAME	= scene

LIBSRCS		= \
			DList.cxx \
			Fog.cxx \
			Projection.cxx \
			Scene.cxx

FKLINK		= \
			-lFK4_base.$(VERNAME) \
			-lFK4_material.$(VERNAME) \
			-lFK4_math.$(VERNAME) \
			-lFK4_shape.$(VERNAME) \
			-lFK4_model.$(VERNAME)

FKLINK_G	= \
			-lFK4_base_g.$(VERNAME) \
			-lFK4_material_g.$(VERNAME) \
			-lFK4_math_g.$(VERNAME) \
			-lFK4_shape_g.$(VERNAME) \
			-lFK4_model_g.$(VERNAME)

include ../makeinclude
