BASENAME	= scene

LIBSRCS		= \
			DList.cxx \
			Fog.cxx \
			Projection.cxx \
			Scene.cxx

FKLINK		= \
			-lFK3_base.$(VERNAME) \
			-lFK3_material.$(VERNAME) \
			-lFK3_shape.$(VERNAME) \
			-lFK3_model.$(VERNAME)

FKLINK_G	= \
			-lFK3_base_g.$(VERNAME) \
			-lFK3_material_g.$(VERNAME) \
			-lFK3_shape_g.$(VERNAME) \
			-lFK3_model_g.$(VERNAME)

include ../makeinclude
