#! /usr/bin/env perl

use Getopt::Std;

%opts = ();

getopts ("r", \%opts);

foreach $svgName (@ARGV) {
	next if $svgName !~ /.svg$/;
	$epsName = $svgName;
	$epsName =~ s/.svg$/.eps/;

	if($opts{"r"} == 1) {
		$com = &rsvg($svgName, $epsName);
	} else {
		$com = &inkscape($svgName, $epsName);
	}

	system($com);
}

0;

sub inkscape {
	($svgName_, $epsName_) = @_;
	$com_ = "inkscape --file=";
	$com_ .= $svgName_;
	$com_ .= " --export-eps=";
	$com_ .= $epsName_;
	return ($com_);
}

sub rsvg {
	($svgName_, $epsName_) = @_;
	$com_ = "rsvg-convert ";
	$com_ .= $svgName_;
	$com_ .= " -z 0.8 --format=ps -o ";
	$com_ .= $epsName_;
	return ($com_);
}

