#! /usr/bin/env perl

use Getopt::Std;

%opts = ();

getopts ("ir", \%opts);

foreach $svgName (@ARGV) {
	next if $svgName !~ /.svg$/;
	$pngName = $svgName;
	$pngName =~ s/.svg$/.png/;

	if($opts{"i"} == 1) {
	    $com = "inkscape --export-area-drawing --export-dpi=144 --file=";
	    $com .= $svgName;
	    $com .= " --export-png=";
	    $com .= $pngName;
	} else {
	    $com = "convert -trim -density 600 -resize 1024x ";
	    $com .= $svgName;
	    $com .= " ";
	    $com .= $pngName;
	}
	if(!(-f $pngName)) {
		system($com);
	}	
}

0;

