#! /usr/bin/env perl

use Getopt::Std;

%opts = ();

getopts ("ir", \%opts);

foreach $svgName (@ARGV) {
	next if $svgName !~ /.svg$/;
	$epsName = $svgName;
	$epsName =~ s/.svg$/.eps/;

	if($opts{"i"} == 1) {
	    $com = "inkscape --file=";
	    $com .= $svgName;
	    $com .= " --export-eps=";
	    $com .= $epsName;
	} else {
	    $com = "rsvg-convert ";
	    $com .= $svgName;
	    $com .= " -z 0.8 --format=ps -o ";
	    $com .= $epsName;
	}

	if(!(-f $epsName)) {
		system($com);
	}	
}

0;

