#! /usr/bin/env perl

use Getopt::Std;

%opts = ();

getopts ("i:r", \%opts);

foreach $svgName (@ARGV) {
	next if $svgName !~ /.svg$/;
	$pngName = $svgName;
	$pngName =~ s/.svg$/.png/;

	if(exists $opts{"r"}) {
		$com = "rsvg-convert ";
		$com .= $svgName;
		$com .= " -z 0.8 --format=png -o ";
		$com .= $pngName;
	} else {
		$com = "inkscape --export-area-drawing --file=";
		$com .= $svgName;
		$com .= " --export-png=";
		$com .= $pngName;
		if(exists $opts{"i"}) {
			$com .= " --export-dpi=";
			$com .= $opts{"i"};
		}
	}
		
	system($com);
}

0;

