BASENAME	= math

LIBSRCS		= \
			FVecArray.cxx \
			GenMatrix.cxx \
			GenVector.cxx \
			Math.cxx \
			Matrix.cxx \
			Plane.cxx \
			Quaternion.cxx \
			Vector.cxx

FKLINK		= -lFK3_base.$(VERNAME)

FKLINK_G	= -lFK3_base_g.$(VERNAME)

include ../makeinclude
