LIBSRCS = \
		GenMatrix.cxx \
		GenVector.cxx \
		Math.cxx \
		Matrix.cxx \
		Plane.cxx \
		Quaternion.cxx \
		Vector.cxx

LIBRARY_S	= $(STATIC_DIR)/libFK3_math.a
LIBRARY_SG	= $(STATIC_DIR)/libFK3_matn_g.a
LIBRARY_D	= $(DYNAMIC_DIR)/libFK3_math.3.1.dylib
LIBRARY_DG	= $(DYNAMIC_DIR)/libFK3_math_g.3.1.dylib
LIBRARY		= $(LIBRARY_S) 
FKLINK		= -lFK3_base.3.1
FKLINK_G	= -lFK3_base_g.3.1
FKLIBS		=

include ../makeinclude
