BASENAME	= math

LIBSRCS		= \
			Angle.cxx \
			FVecArray.cxx \
			GenMatrix.cxx \
			GenVector.cxx \
			Math.cxx \
			Matrix.cxx \
			Plane.cxx \
			Quaternion.cxx \
			Vector.cxx

FKLINK		= \
			-lFK4_base.$(VERNAME) \
			-lFK4_material.$(VERNAME)

FKLINK_G	= \
			-lFK4_base_g.$(VERNAME) \
			-lFK4_material_g.$(VERNAME)

include ../makeinclude
