BASENAME	= material

LIBSRCS		= \
			ColorArray.cxx \
			MatExample.cxx \
			Material.cxx \
			Palette.cxx

FKLINK		= -lFK3_base.$(VERNAME)

FKLINK_G	= -lFK3_base_g.$(VERNAME)

include ../makeinclude
